Feat/update accordion item
nordnet/ui pull request #1006
Opened 2021-11-24 15:54 UTC by kk-11

2021-11-24 17:08 UTC, mic1000 approved these changes

2021-11-25 07:56 UTC, frlutz reviewed
Just some minor comments! Otherwise looks good, nice work!

2021-11-25 07:56 UTC, frlutz commented on src/Molecules/AccordionItem/AccordionItem.tsx
> +const Button = styled.button<{ withChevron?: boolean; disabled?: boolean }>`
Was there any particular reason not to have `withChevron` and `disabled` as transient props?

2021-11-25 07:56 UTC, frlutz commented on src/Molecules/AccordionItem/AccordionItem.tsx
> +import styled, { css } from 'styled-components';
What is the reasoning behind `css` in this file? It seems to only be used in what's already `styled` components, so just returning the complete string instead of `css..` would yield the same behaviour?

2021-11-25 07:56 UTC, frlutz commented on src/Molecules/AccordionItem/AccordionItem.tsx
> +const MovingChevron = styled(Icon.ChevronUp8)<{ disabled?: boolean; expanded: boolean }>`
Minor and optional, but "Moving" I don't think it's needed since it's the only type of chevron that should exist right?

2021-11-25 08:51 UTC, jesperwiner commented on src/Molecules/AccordionItem/AccordionItem.tsx
> +const Button = styled.button<{ withChevron?: boolean; disabled?: boolean }>`
think should be put back as $

2021-11-25 09:01 UTC, jesperwiner commented on src/Molecules/AccordionItem/AccordionItem.tsx
> +import styled, { css } from 'styled-components';
It should work just the same without,  the css function we use when preparing other blocks to be used inside a styled func

2021-11-25 09:03 UTC, jesperwiner requested changes
think you could do what Fredrik suggests, its more inline with whats already in UI

2021-11-25 11:23 UTC, kk-11 commented on src/Molecules/AccordionItem/AccordionItem.tsx
> +const Button = styled.button<{ withChevron?: boolean; disabled?: boolean }>`
In this instance we were previously passing $disabled and disabled as props to the Button (see below). For me generally styled components has been smart enough to remove appropriately named props from being rendered to the dom. For this one though, isn't the desired functionality to have disabled applied to the button? It will still pass as a prop, and now we can remove the extra $disabled being passed without losing the functionality. withChevron is far enough from being anything like an intrinsic attribute that styled components will remove it automatically. Personally I think we should reserve the $ for when it's really needed like expanded on the svg component in this file. It's cool functionality but I would prefer to have p={p} rather than $p={p}. As it kind of confuses what it's supposed to be used for.

2021-11-25 11:37 UTC, jesperwiner commented on src/Molecules/AccordionItem/AccordionItem.tsx
> +const Button = styled.button<{ withChevron?: boolean; disabled?: boolean }>`
ok

2021-11-25 14:20 UTC, jesperwiner approved these changes

2021-11-25 14:31 UTC, merged