Promotion banner
nordnet/ui pull request #1163
Opened 2022-07-28 11:22 UTC by mic1000

This is the new promotion banner component. Today, the "marketing image banner" is only used on the accounts overview page. This promotion banner can appear on any page with either a circle image or Icon Badge, along with a title, description and single call to action Pill Button.

The banner can be permanently fixed or dismissible, it also has a full width or column width state.

[Design Documentation](https://www.figma.com/file/eBY9GFogdepN8P5UWEclrE/One-Flow?node-id=1850%3A150583)

Components

Photo or Icon Badge
Title
Description
Pill Button
Cross - can be fixed OR dismissible
Background
Default
Light mode - Blue 100
Dark mode - Blue 800
Green - Shareville
Light mode - Green 100
Dark mode - Green 800
White
Light mode - White
Dark mode - Grey 800

2022-07-28 11:56 UTC, kk-11 approved these changes

2022-07-29 09:22 UTC, jonnakollin approved these changes

2022-07-29 09:27 UTC, merged

2022-07-29 09:28 UTC, hardikkaji requested changes

2022-07-29 09:28 UTC, hardikkaji commented on src/Molecules/PromotionBanner/PromotionBanner.types.ts
> +  // isMobile?: boolean;
remove this!

2022-07-29 09:28 UTC, hardikkaji commented on src/Molecules/PromotionBanner/PromotionBanner.tsx
> +  const handleClose = () => {
try function with useCallback!

2022-07-29 09:28 UTC, hardikkaji commented on src/Molecules/PromotionBanner/PromotionBanner.tsx
> +  const getColor = (t: any) => {
try function with useCallback!

2022-07-29 09:28 UTC, hardikkaji commented on src/Molecules/PromotionBanner/PromotionBanner.tsx
> +  const getColor = (t: any) => {
There is Theme type in theme.types.ts! I would recommend to use it!

2022-07-29 09:33 UTC, mic1000 commented on src/Molecules/PromotionBanner/PromotionBanner.types.ts
> +  // isMobile?: boolean;
I missed that.