Add full screen prop modal
nordnet/ui pull request #689
Opened 2020-09-15 12:55 UTC by bergholmm

2020-09-15 13:15 UTC, victoriatomzik approved these changes

2020-09-16 07:14 UTC, jesperwiner requested changes

2020-09-16 07:14 UTC, jesperwiner commented on src/Molecules/Modal/Modal.stories.tsx
> +              Modals should be used with care as they are quite intrusive on the user experience and
Please adjust story to reflect the true intention of "not full screen mobile" with a smaller one like the design with "Are you sure you want to quit" to make it clear what it looks like.

2020-09-16 07:14 UTC, jesperwiner commented on src/Molecules/Modal/Modal.stories.tsx
> +  name: 'Not full width mobile',
screen instead of width

2020-09-16 07:41 UTC, bergholmm commented on src/Molecules/Modal/Modal.stories.tsx
> +  name: 'Not full width mobile',
Updated

2020-09-16 07:41 UTC, bergholmm commented on src/Molecules/Modal/Modal.stories.tsx
> +              Modals should be used with care as they are quite intrusive on the user experience and
Updated

2020-09-16 08:34 UTC, jesperwiner approved these changes

2020-09-16 09:19 UTC, Vikingjonsson approved these changes

2020-09-16 09:23 UTC, merged