Feature/add pagination component
nordnet/ui pull request #702
Opened 2020-09-23 15:18 UTC by toblu

Add Pagination component

2020-09-24 06:06 UTC, nn-davsko approved these changes
Looks great, well done!

2020-09-24 06:31 UTC, fredriklu approved these changes

2020-09-24 06:31 UTC, fredriklu commented on src/Molecules/Pagination/DesktopPagination.tsx
> +    if (p.numberOfPages >= 8 && p.numberOfPages >= 13) return BETWEEN_8_AND_13_PAGES_WIDTH;
It seems like the true width of this example in the story is actually 200px wide? How does it come that this default width is larger than the 999 example on start? (If you refer to the distance between the chevrons). 

Also, the 999 example increases in size as the width of the numbers increase (e.g. if you navigate to page 996), but it doesn't for the other examples. Shouldn't all examples be adaptive if possible?

2020-09-24 06:31 UTC, fredriklu commented on src/Molecules/Pagination/Pagination.stories.tsx
> +  <PaginationWrapper totalItems={10} itemsPerPage={1} compact />
This story redirects weirdly in the vercel-preview, just wanted to let you know!

2020-09-24 06:32 UTC, fredriklu commented
Great that you've added documentation right off the bat! 🌟

2020-09-24 06:41 UTC, toblu commented on src/Molecules/Pagination/DesktopPagination.tsx
> +    if (p.numberOfPages >= 8 && p.numberOfPages >= 13) return BETWEEN_8_AND_13_PAGES_WIDTH;
Really good catch! That is of course not the way it should be, something must have happened here... Looking into it now

2020-09-24 06:45 UTC, toblu commented on src/Molecules/Pagination/DesktopPagination.tsx
> +    if (p.numberOfPages >= 8 && p.numberOfPages >= 13) return BETWEEN_8_AND_13_PAGES_WIDTH;
Ah, it's the `p.numberOfPages >= 13` that is the culprit here. Since we want to check if it's between 8 and 13 pages it should ofc be `p.numberOfPages <= 13` 🙈 . I will fix that!

2020-09-24 06:54 UTC, mhogler approved these changes

2020-09-24 07:01 UTC, toblu commented on src/Molecules/Pagination/Pagination.stories.tsx
> +  <PaginationWrapper totalItems={10} itemsPerPage={1} compact />
How do you mean? It looks fine from what I can tell

2020-09-24 07:04 UTC, smithsamyan commented on src/Molecules/Pagination/Pagination.tsx
> +      onPageChange(Number(e.target.textContent));
Tip: It would be better if you send the actual page number rather than using e.target.textContent. TextContent may become inaccurate if we have any formatting of the text or add visually hidden data for a11y. This wouldn't for example work if we had thousand separators

2020-09-24 07:12 UTC, toblu commented on src/Molecules/Pagination/Pagination.tsx
> +      onPageChange(Number(e.target.textContent));
Yes, that is a good point 👍  Will update

2020-09-24 07:44 UTC, smithsamyan commented on src/Molecules/Pagination/Pagination.tsx
> +  currentPage,
tip: In the ui library, we try  to implement both controlled and uncontrolled behaviours. You don't have to do it now but we should implement pagination with uncontrolled behaviour :)

2020-09-24 08:47 UTC, toblu commented on src/Molecules/Pagination/Pagination.tsx
> +      onPageChange(Number(e.target.textContent));
Fixed in d5bc24e

2020-09-24 10:23 UTC, mjmonline requested changes
So in this repo we try to keep high standard and we try to follow the "DND Definition of done checklist" in confluence, message me or any of the #ui-task-force members for the link.

So about buttons and links, if we are redirecting the user to let's say "page2" then the logical solution would be to use a link with the href="?page='2'" or something. If the pagination on the other hand is used for a let's say sub section of a page and it's not really considered as a "page2" then you're not redirecting so a button would be fine.

Also I'm not sure this PR has been tested with a screen reader because the result was not so user friendly, will post some videos explaining

2020-09-24 10:23 UTC, mjmonline commented on src/Molecules/Pagination/MobilePaginationDefault.tsx
> +  width: ${(p) => Math.min(p.numberOfPages, MAX_NUMBER_ITEMS) * ITEMS_TOTAL_WIDTH}px;
kinda bug prone, is there a reason to set the width here? Can it be solved with just paddings?

2020-09-24 10:23 UTC, mjmonline commented on src/Molecules/Pagination/MobilePaginationDefault.tsx
> +  width: 40px;
units

2020-09-24 10:23 UTC, mjmonline commented on src/Molecules/Pagination/MobilePaginationCompact.tsx
> +    }}
same here, why not a `<button>`?

2020-09-24 10:23 UTC, mjmonline commented on src/Molecules/Pagination/MobilePaginationCompact.tsx
> +  width: 40px;
units

2020-09-24 10:23 UTC, mjmonline commented on src/Molecules/Pagination/DesktopPagination.tsx
> +    return MORE_THAN_101_PAGES_WIDTH;
see my previous comment on width

2020-09-24 10:23 UTC, mjmonline commented on src/Molecules/Pagination/DesktopPagination.tsx
> +    <Button id="currentPage" variant="neutral" disabled={active} onClick={onClick}>
you're not using the id but you have several buttons now with same id

2020-09-24 10:23 UTC, mjmonline commented on src/Molecules/Pagination/DesktopPagination.tsx
> +    <Button id="currentPage" variant="neutral" disabled={active} onClick={onClick}>
Also in mobile you use links, whats the difference?

2020-09-24 10:45 UTC, mjmonline commented
This is recording with VoiceOver on mac https://streamable.com/49ae9s

Firstly you should wrap the pagination in a `<nav role="navigation">` and label that element with for example `aria-label` so the user knows what they will be navigating.

Secondly your back and forward button just reads "button", it could be impossible for a visually impaired person to know what's going to happen if the button is clicked. But for a normal user he would just see the arrows and figure it out. Here I would suggest you use `<VisuallyHidden>` atom and write something like "go to previous page".

Thirdly the numbered buttons also just say "button 2", "button 3" and so on. Rather you would like it to read "go to page 2" or "go to page 3"

2020-09-24 10:53 UTC, mjmonline commented
This is recording of a old Pagination component in our old ui-kit: https://streamable.com/ykwijm

https://github.com/nordnet/nordnet-ui-kit/tree/master/src/components/pagination

2020-09-24 12:00 UTC, toblu commented on src/Molecules/Pagination/Pagination.tsx
> +  currentPage,
Fixed in cd1ba98

2020-09-24 12:32 UTC, toblu commented on src/Molecules/Pagination/__snapshots__/Pagination.stories.storyshot
> +      numberOfPages={1}
Thanks, good catch. Fixed in d7dbfae

2020-09-24 12:52 UTC, mhogler commented on src/Molecules/Pagination/MobilePaginationDefault.tsx
> +  width: ${(p) => Math.min(p.numberOfPages, MAX_NUMBER_ITEMS) * ITEMS_TOTAL_WIDTH}px;
The reason why we must calculate the width is so that we can correctly position the chevron buttons from the beginning, otherwise they move as the user browses through the pages.

Imagine you're on page page 1 out of 12, and then you're stepping to page 4. The chevron buttons should stay in the same position even though the total width of the page items increases on page 4. Hopfully the screenshots makes this more clear.

We'd also like to make this less hard coded, but could not find any other way of solving it with paddings etc, do you have another suggestion of how it could be solved?
![Screenshot 2020-09-24 at 14 43 41](https://user-images.githubusercontent.com/16958673/94147397-84270580-fe75-11ea-9bd7-a7ca6f26e1dd.png)
![Screenshot 2020-09-24 at 14 44 19](https://user-images.githubusercontent.com/16958673/94147369-7cfff780-fe75-11ea-8691-4bbce2b38a52.png)

2020-09-24 13:56 UTC, mhogler commented on src/Molecules/Pagination/MobilePaginationDefault.tsx
> +  width: 40px;
fixed in 93b6de8

2020-09-24 13:57 UTC, mhogler commented on src/Molecules/Pagination/MobilePaginationCompact.tsx
> +  width: 40px;
fixed in 93b6de8

2020-09-25 08:44 UTC, toblu commented on src/Molecules/Pagination/MobilePaginationDefault.tsx
> +    }}
Good point, it should be a `<button>`. Fixed in 3024c70

2020-09-25 08:44 UTC, toblu commented on src/Molecules/Pagination/MobilePaginationCompact.tsx
> +    }}
Fixed in 3024c70

2020-09-25 08:45 UTC, toblu commented on src/Molecules/Pagination/DesktopPagination.tsx
> +    <Button id="currentPage" variant="neutral" disabled={active} onClick={onClick}>
Fixed in 3024c70

2020-09-25 11:44 UTC, mhogler commented on src/Molecules/Pagination/Pagination.md
> +| currentPage  | number                 | N/A     | The current page number          |
Fixed in a9617b6

2020-09-25 13:55 UTC, toblu commented
@mjmonline Thank you for your thorough review and great inputs! We have addressed all your comments, please take a look again :)

2020-09-28 09:45 UTC, mjmonline approved these changes

2020-09-28 09:45 UTC, mjmonline commented on src/Molecules/Pagination/DesktopPagination.tsx
> +  list-style-type: none;
This is `Atom/List`

2020-09-28 09:45 UTC, mjmonline commented on src/Molecules/Pagination/DesktopPagination.tsx
> +    const NUMBER_WIDTH = p.theme.spacing.unit(4.5);
We don't really have any fractions of a unit in the UI, somewhere there has been a mistake because designers is also aware of the 4px unit. It's not a blocker, I'm just informing

2020-09-28 09:45 UTC, mjmonline commented on src/Molecules/Pagination/MobilePaginationDefault.tsx
> +  list-style-type: none;
same, can be reused

2020-09-28 09:45 UTC, mjmonline commented on src/Molecules/Pagination/DesktopPagination.tsx
> +      aria-label={`${isCurrentPage ? 'Current Page:' : 'Go to'} page ${children}`}
Would be nice if devs can override the text with a prop and same for all other a11y texts

2020-09-29 12:35 UTC, mhogler commented on src/Molecules/Pagination/DesktopPagination.tsx
> +    const NUMBER_WIDTH = p.theme.spacing.unit(4.5);
Indeed, we thought about this as well, unfortunately with the current design, this was the only way we could make it work. Using either 4 or 5 units doesn't look good

2020-09-29 12:37 UTC, merged