Feat/hero card
nordnet/ui pull request #723
Opened 2020-10-14 14:50 UTC by Vikingjonsson

2020-10-14 14:52 UTC, Vikingjonsson commented
Misguiding branch name, the component is now called SelectionCard. This aims to replace "GuidanceCard" and "IconCard".

2020-10-14 14:57 UTC, victoriatomzik approved these changes

2020-10-14 15:09 UTC, Vikingjonsson commented on src/Molecules/SelectionCard/SelectionCard.mdx
> +# Multi Step Progress
will fix

2020-10-15 06:42 UTC, stigdanielek approved these changes

2020-10-15 07:10 UTC, crewneck approved these changes

2020-10-15 07:10 UTC, LifeofMichal approved these changes

2020-10-15 08:29 UTC, mjmonline requested changes
I can't reach the component with keyboard or screen reader. Also the component is controlled only, would be nice to have the option to run it with uncontrolled behavior

2020-10-15 14:07 UTC, kmelkon approved these changes

2020-10-16 07:59 UTC, mjmonline approved these changes
👍

2020-10-16 08:01 UTC, merged