Fix/multistepprogress
nordnet/ui pull request #737
Opened 2020-10-22 08:46 UTC by victoriatomzik

2020-10-22 08:53 UTC, alvelid approved these changes

2020-10-22 08:57 UTC, kmelkon approved these changes

2020-10-22 09:01 UTC, Vikingjonsson commented on src/Molecules/MultiStepProgress/TopLevel/TopLevel.tsx
> +const Wrapper = styled(Box)<InternalProps>`
does this need InternalProps?

2020-10-22 09:05 UTC, victoriatomzik commented on src/Molecules/MultiStepProgress/TopLevel/TopLevel.tsx
> +const Wrapper = styled(Box)<InternalProps>`
I just saw it myself and removed it ^_^

2020-10-22 09:34 UTC, mjmonline requested changes

2020-10-22 09:34 UTC, mjmonline commented on src/Molecules/MultiStepProgress/TopLevel/TopLevel.tsx
> -  & + & {
You probably don't want margin-top or border above the first item

2020-10-22 09:34 UTC, mjmonline commented on src/Molecules/MultiStepProgress/TopLevel/TopLevel.tsx
> +    border-top: ${(p) => p.theme.spacing.unit(0.25)}px solid ${(p) => p.theme.color.divider};
I see that you just copy pasted but here use 1px instead of 0.25 units because this should not get bigger if our unit changes also we don't do fractions of a unit

2020-10-22 09:34 UTC, mjmonline commented on src/Molecules/MultiStepProgress/TopLevel/TopLevel.tsx
> +    margin-left: ${(p) => (p.$isInDrawer ? -p.theme.spacing.unit(3) : 0)}px;
why is this?

2020-10-22 09:35 UTC, mjmonline commented on src/Molecules/MultiStepProgress/TopLevel/TopLevel.tsx
> +    margin-left: ${(p) => (p.$isInDrawer ? -p.theme.spacing.unit(3) : 0)}px;
There is no story with the multistep in a drawer, wanna create one?

2020-10-22 15:57 UTC, Vikingjonsson approved these changes

2020-10-23 07:58 UTC, mjmonline requested changes

2020-10-23 07:58 UTC, mjmonline commented on src/Molecules/MultiStepProgress/TopLevel/TopLevel.tsx
> +    li + li & {
This is a little dangerous because it says any `li`that has a direct sibling `li` that also has the `Wrapper` as a child. Which in this case works but this is a UI component and it could be used on different pages with different html. So keep it safe by doing `ListItem + ListItem` instead of `li + li`

2020-10-23 08:11 UTC, mjmonline approved these changes

2020-10-23 08:12 UTC, merged