Feat/date picker with range
nordnet/ui pull request #757
Opened 2020-11-11 13:46 UTC by fredriklu

This is the first iteration to avoid one giant PR in the end. This also contains bug fixes for regular date picker that was encountered when implementing the range.

This contains small accessibility updates as well, but these have not been fully focused and will be revised in another PR.

2020-11-12 07:08 UTC, nn-davsko commented on src/Molecules/DatePicker/DatePicker.tsx
> +  const handleRegularDateClick = useCallback(
is there any way the naming of handleRegularDateClick & handleOnDateClick could be more descriptive?

2020-11-12 07:15 UTC, nn-davsko commented on src/Molecules/DatePicker/DatePickerRange.stories.tsx
> +export const Default = () => (
Are these all the stories that you need to clearly display different states of the range date picker? I'm not sure myself but I just want to point out that according to our DoD we should have stories describing all different states that a component could have (to a reasonable degree of course it's up to you to decide).

2020-11-12 07:16 UTC, nn-davsko approved these changes
Looks really good but a fairly large PR I might have missed something.

2020-11-12 08:03 UTC, toblu commented on src/Molecules/DatePicker/Calendar/Calendar.tsx
> +const calendarDayRefs = [...Array(NUMBER_OF_VISIBLE_WEEKS)].map(() => {
I'm not sure if there could be potential consequences of using `createRef` directly in the file outside of the component, since `createRef` is typically only used in class components. I'm a little unsure how this would behave with multiple datepickers since the ref object might not be tied to a specific component instance.

I would suggest you create it using `useRef` instead inside the component. You can create a ref that can store an array of elements. Something like this:
```
const calendarDayRefs = useRef(Array(NUMBER_OF_VISIBLE_WEEKS).fill(Array(NUMBER_OF_VISIBLE_DAYS).fill(null)))
```

2020-11-12 08:34 UTC, almightybruce commented on src/Molecules/DatePicker/Calendar/CalendarDay.tsx
> +        onFocus={() => onFocus()}
not necessary to curry this :)

2020-11-12 08:34 UTC, almightybruce commented on src/Molecules/DatePicker/Calendar/CalendarDay.tsx
> +      if (disabled || (typeof enabled === 'boolean' && !enabled)) return 'label';
this condition could be made into a const, since its used on 104 as well :)

2020-11-12 08:34 UTC, almightybruce commented on src/Molecules/DatePicker/DatePicker.tsx
> +    selectedEndDate: selectedEndDateProp,
is this selectedStartDate when doing a range? if so, it might be worth to document that

2020-11-12 08:34 UTC, almightybruce commented on src/Molecules/DatePicker/DatePicker.tsx
> +      setInputValue(format(date, dateFormat, options));
does this still handle controlled behaviour?

2020-11-12 08:34 UTC, almightybruce commented on src/Molecules/DatePicker/DatePicker.tsx
> +      })();
maybe add a comment that this is self invoked and why

2020-11-12 08:48 UTC, almightybruce commented on src/Molecules/DatePicker/DatePicker.tsx
> +      })();
maybe add a comment that this is self invoked and why

2020-11-12 08:49 UTC, almightybruce commented on src/Molecules/DatePicker/Calendar/Calendar.tsx
> +            })();
maybe add a comment that this is self invoked and why

2020-11-12 08:51 UTC, gustav-pettersson-nordnet commented on src/Molecules/DatePicker/DatePicker.tsx
> +        : `${format(startDate, dateFormat, options)} - ${format(endDate, dateFormat, options)}`;
Might be nice to add "-" to a constant.

2020-11-12 09:15 UTC, almightybruce commented on src/Molecules/DatePicker/Calendar/Calendar.tsx
> +                withinRange={
without knowing what this does, is there a better name for it? like `dateIsWithinCurrentRange`

2020-11-12 09:27 UTC, toblu commented on src/Molecules/DatePicker/Calendar/Calendar.tsx
> +    if (R.isNil(focusedWeek) || R.isNil(focusedDay)) {
Perhaps it would be a good idea to call `event.stopPropagation()` here? Since you don't want these events to "bubble" up to parent elements, right?

2020-11-12 09:30 UTC, toblu commented on src/Molecules/DatePicker/Calendar/Calendar.tsx
> +          } else if (focusedWeek !== 0) {
Any reason that you're using `focusedWeek !== 0` here and not `focusedWeek > 0`? `focusedWeek` should never be less than zero, right?

2020-11-12 09:35 UTC, toblu commented on src/Molecules/DatePicker/Calendar/Calendar.tsx
> +          {week.map((d, dayIndex) => {
Perhaps rename `d` to `day` here. `d` could be anything

2020-11-12 09:40 UTC, toblu commented on src/Molecules/DatePicker/Calendar/Calendar.tsx
> +                edgeDay={edgeDay}
Perhaps it would be easier to split this into two props: `isFirstDay` & `isLastDay` or something like that? Not so important, so feel free to leave it as it is if you prefer that. Just bringing it up as something you could consider :)

2020-11-12 09:45 UTC, toblu commented on src/Molecules/DatePicker/Calendar/CalendarDay.tsx
> +      if (disabled || (typeof enabled === 'boolean' && !enabled)) return 'label';
is the `typeof` check necessary here? in what case is `enabled` not a boolean?

2020-11-12 09:58 UTC, robinandersson commented on src/Molecules/DatePicker/Calendar/Calendar.tsx
> +const calendarDayRefs = [...Array(NUMBER_OF_VISIBLE_WEEKS)].map(() => {
The aren't actually the same, spreading like we do yields an array with 7 undefined entries, not spreading the array yields an array with 7 "empty" entries... Don't ask me why, but it does change the execution and we couldn't get it to work without spreading the arrays.

2020-11-12 10:02 UTC, nn-davsko requested changes
We need to fix A11y or at least have another look at it. It seems voice over does not work when tab-selecting new dates in the calendar view.

2020-11-12 10:03 UTC, fredriklu commented on src/Molecules/DatePicker/DatePicker.tsx
> +    selectedEndDate: selectedEndDateProp,
Do you mean `selectedDate`? If so: Yes. It has kept that naming since `selectedStartDate` would be confusing for the regular DatePicker.

Do you propose leaving a comment?

2020-11-12 10:03 UTC, robinandersson commented on src/Molecules/DatePicker/Calendar/Calendar.tsx
> +          if (!R.isNil(focusedDateObjRef.current)) onClick(new Date(focusedDateObjRef.current));
If it's the second part you're referring to, i.e. what we pass to the onClick handler then yes, it will be set. But we still need to create a new Date object to create a new reference (onClick handler might mutate focus object, thus opening up the potential for a whole lot of worms).

2020-11-12 10:17 UTC, fredriklu commented
> We need to fix A11y or at least have another look at it. It seems voice over does not work when tab-selecting new dates in the calendar view.

@nn-davsko This is known, see the first comment/description of the PR. Since this PR is already quite large, and/but still improves the existing regular DatePicker which seems to lack A11y features as well, we decided to create the PR anyway.

2020-11-12 10:24 UTC, fredriklu commented on src/Molecules/DatePicker/DatePicker.tsx
> +      })();
This seems excessive. This is a quite common pattern and adding an explanation of IIFE and why would be quite a meaty comment. 

An alternative would be refactoring it to a proper function, but we feel that would add unnecessary complexity.

2020-11-12 10:28 UTC, fredriklu commented on src/Molecules/DatePicker/DatePicker.tsx
> +      })();
See reply on first instance.

2020-11-12 10:29 UTC, fredriklu commented on src/Molecules/DatePicker/Calendar/Calendar.tsx
> +            })();
See reply on first instance.

2020-11-12 10:30 UTC, fredriklu commented on src/Molecules/DatePicker/DatePicker.tsx
> +        : `${format(startDate, dateFormat, options)} - ${format(endDate, dateFormat, options)}`;
Do you mean create e.g. const INPUT_SEPARATOR = '-'?

2020-11-12 10:33 UTC, fredriklu commented on src/Molecules/DatePicker/Calendar/Calendar.tsx
> +                withinRange={
Since it only handles styling (the grey background and edge of month fade), and there can only be one range, therefore this seems a bit excessive, especially since the code below also indicates what it controls.

2020-11-12 10:43 UTC, nn-davsko commented
> > We need to fix A11y or at least have another look at it. It seems voice over does not work when tab-selecting new dates in the calendar view.
> 
> @nn-davsko This is known, see the first comment/description of the PR. Since this PR is already quite large, and/but still improves the existing regular DatePicker which seems to lack A11y features as well, we decided to create the PR anyway.

Ok sounds fair, I missed that in the comments.

2020-11-12 10:43 UTC, nn-davsko approved these changes

2020-11-12 11:25 UTC, almightybruce commented on src/Molecules/DatePicker/DatePicker.tsx
> +    selectedEndDate: selectedEndDateProp,
Yes

2020-11-12 11:43 UTC, almightybruce commented on src/Molecules/DatePicker/Calendar/Calendar.tsx
> +          if (!R.isNil(focusedDateObjRef.current)) onClick(new Date(focusedDateObjRef.current));
So i think you should explain that in a comment so nobody refactors it away

2020-11-12 11:51 UTC, almightybruce commented on src/Molecules/DatePicker/Calendar/Calendar.tsx
> +                withinRange={
It doesn't hurt to be clear. I think you should at least put an `is` infront

2020-11-12 11:55 UTC, almightybruce commented on src/Molecules/DatePicker/DatePicker.tsx
> +      })();
Not saying you should explain IIFE's and their existence. Just saying the `()` is easily missed and since there's no obvious reason to do an IIFE, a heads up would have been nice.

2020-11-12 12:10 UTC, toblu commented on src/Molecules/DatePicker/Calendar/Calendar.tsx
> +const calendarDayRefs = [...Array(NUMBER_OF_VISIBLE_WEEKS)].map(() => {
Just a comment regarding why it was necessary to use the spread operator here. The `Array()` function creates an array of the specified length, however it does not give the elements any value (`undefined` is a value). Array elements without a value are not enumerable and that is why `.map()` has no effect on an array with only `empty` elements. When you use the spread operator, all the elements in the newly created array are initialized with the value `undefined` and that is the reason why you are able to use `.map()` on the new array

2020-11-12 16:04 UTC, fredriklu commented on src/Molecules/DatePicker/Calendar/Calendar.tsx
> +const calendarDayRefs = [...Array(NUMBER_OF_VISIBLE_WEEKS)].map(() => {
.fill did not create unique ref:s, but useRef is now implemented!

2020-11-13 07:44 UTC, toblu commented on src/Molecules/DatePicker/Calendar/Calendar.tsx
> +      return [...Array(NUMBER_OF_VISIBLE_DAYS)].reduce((acc) => {
Doesn't this reduce function behave just like a regular .map here? In that case I would say it would be easier to understand this line if you only used .map.

`[...Array(NUMBER_OF_VISIBLE_DAYS)].map(React.createRef)`

2020-11-13 08:27 UTC, robinandersson commented on src/Molecules/DatePicker/Calendar/Calendar.tsx
> +const calendarDayRefs = [...Array(NUMBER_OF_VISIBLE_WEEKS)].map(() => {
Ooh, nice explanation @toblu! Did not know this :)

2020-11-16 10:34 UTC, almightybruce approved these changes
stellar work!

2020-11-16 15:17 UTC, fredriklu commented on src/Molecules/DatePicker/DatePicker.tsx
> +    selectedEndDate: selectedEndDateProp,
After further discussion, we decided to leave it as is.

2020-11-16 15:24 UTC, fredriklu commented on src/Molecules/DatePicker/DatePicker.tsx
> +      })();
After further discussion, we don't think requires special treatment more than any other pattern. We have not made these kind of comments for e.g. curried functions previously.

2020-11-16 15:28 UTC, gustav-pettersson-nordnet commented on src/Molecules/DatePicker/DatePicker.tsx
> +        : `${format(startDate, dateFormat, options)} - ${format(endDate, dateFormat, options)}`;
Yes :) Mostly to see that is not a subtraction :) but the char "-"

2020-11-17 05:19 UTC, toblu approved these changes
Great job guys! ⭐

2020-11-17 08:34 UTC, robinandersson commented
Thanks! 🙂

2020-11-17 13:34 UTC, frozzare approved these changes

2020-11-17 14:44 UTC, fredriklu commented on src/Molecules/DatePicker/DatePicker.tsx
> +        : `${format(startDate, dateFormat, options)} - ${format(endDate, dateFormat, options)}`;
This seems kind of extensive for just one character, especially since it's within a template string that's named rangeDateString

2020-11-17 15:44 UTC, merged