Feat/showmore
nordnet/ui pull request #759
Opened 2020-11-13 13:37 UTC by victoriatomzik

2020-11-13 14:09 UTC, kmelkon requested changes

2020-11-13 14:09 UTC, kmelkon commented on src/Organisms/ShowMore/ShowMore.tsx
> +  // @ts-ignore
this is not a good sign usually :D what's it complaining about?

2020-11-13 14:09 UTC, kmelkon commented on src/Organisms/ShowMore/useOverflow.ts
> +import { throttle } from 'lodash';
I'm pretty sure there's a way to throttle without adding a new dependancy.

2020-11-13 14:10 UTC, kmelkon commented
Looks good! just left a couple of comments

2020-11-13 14:11 UTC, victoriatomzik commented on src/Organisms/ShowMore/ShowMore.tsx
> +  // @ts-ignore
dude... idek
TS2322: Type 'ReactNode' is not assignable to type 'never'. Type 'undefined' is not assignable to type 'never'.

2020-11-13 14:11 UTC, victoriatomzik commented on src/Organisms/ShowMore/useOverflow.ts
> +import { throttle } from 'lodash';
;_;

2020-11-13 14:16 UTC, kmelkon commented on src/Organisms/ShowMore/ShowMore.tsx
> +  // @ts-ignore
hmm we can look into it later but usually TS throws an error cause there's an underlying issue

2020-11-13 14:16 UTC, alvelid approved these changes

2020-11-16 08:19 UTC, jesperwiner approved these changes

2020-11-16 08:26 UTC, merged