Fix/grey quiet placeholder
nordnet/ui pull request #800
Opened 2020-12-08 10:28 UTC by kmelkon

Grey out quiet input's placeholder on focus

2020-12-08 10:45 UTC, ratkosolar commented on src/Molecules/Input/Number/Number.tsx
> +  height: ${(p) => p.size === 's' && p.theme.spacing.unit(8)}px;
using `&&` shorthand causes weird issues in styled components because it returns false when the condition is not met... so basically when size is not 's' it will output invalid css like seen in screenshot
![image](https://user-images.githubusercontent.com/6464604/101473917-b57a8200-394a-11eb-951e-c85a07e5a23c.png)

2020-12-08 10:52 UTC, kmelkon commented on src/Molecules/Input/Number/Number.tsx
> +  height: ${(p) => p.size === 's' && p.theme.spacing.unit(8)}px;
Ah I didn't know that, should I just use `''` when the condition is not met?

2020-12-08 11:04 UTC, ratkosolar commented on src/Molecules/Input/Number/Number.tsx
> +  height: ${(p) => p.size === 's' && p.theme.spacing.unit(8)}px;
maybe something like `${(p) => p.size === 's' ? `height: ${p.theme.spacing.unit(8)}` : '' }`
not sure what does this have to do with graying out the placeholder though

2020-12-08 11:04 UTC, victoriatomzik commented on src/Molecules/Input/Number/Number.tsx
> +  height: ${(p) => p.size === 's' && p.theme.spacing.unit(8)}px;
jaha, do the ? : dance

2020-12-08 11:08 UTC, kmelkon commented on src/Molecules/Input/Number/Number.tsx
> +  height: ${(p) => p.size === 's' && p.theme.spacing.unit(8)}px;
It didn't adhere to the design for quiet number inputs, but I'll do that and see if it breaks other variants

2020-12-08 15:30 UTC, victoriatomzik commented on src/Molecules/Input/Text/Text.tsx
> +    color: ${(p) => p.variant === 'quiet' && p.theme.color.disabledText};
what is this going to be resolved to when the values are !'quiet' and !disabledText?

2020-12-08 15:34 UTC, kmelkon commented on src/Molecules/Input/Text/Text.tsx
> +    color: ${(p) => p.variant === 'quiet' && p.theme.color.disabledText};
I assume it's gonna use the label colour that's define a few lines above this line but I should add a `? :` to be safe

2020-12-08 15:43 UTC, victoriatomzik commented on src/Molecules/Input/Text/Text.tsx
> +    color: ${(p) => p.variant === 'quiet' && p.theme.color.disabledText};
yeah, either this or you can just add the whole rule in the condition "color" included, so the whole line is kinda on/off, and there's no situation that it returns something like null/undefined

2020-12-08 15:56 UTC, kmelkon commented on src/Molecules/Input/Text/Text.tsx
> +    color: ${(p) => p.variant === 'quiet' && p.theme.color.disabledText};
Hmm that sounds nicer, I'll try that

2020-12-08 16:51 UTC, victoriatomzik approved these changes
NOICE

2020-12-08 17:21 UTC, ratkosolar requested changes

2020-12-08 17:21 UTC, ratkosolar commented on src/Molecules/Input/Text/Text.tsx
> +  ${(p) => (p.disabled ? `&:disabled::placeholder { color: ${p.theme.color.disabledText}}` : '')}
is a combination of `p.disabled` and `&:disabled` necessary?
wouldn't just one be enough or am I wrong?

2020-12-08 17:21 UTC, ratkosolar commented on src/Molecules/Input/Number/Number.tsx
> +  height: ${(p) => (p.variant === 'quiet' ? 'auto' : '')};
but now you have double height property, technically it should work but there is a scenario where this will end up being this
```
height: 40px;
height: ;
```
which is invalid CSS... not sure how styled components will deal with it thought but its safer to do this instead if I got your intention right
```
// its ugly af, I know
const height = css<Pick<Props, "variant" | "size">>`
  ${(p) =>
    p.variant === 'quiet'
      ? 'height: auto'
      : p.size === 's'
        ? `height: ${p.theme.spacing.unit(8)}px`
        : `height: ${p.theme.spacing.unit(10)}px`}
`;

// but you can also do it this way (a bit nicer)
const calculateHeight = (p) => {
  if (p.variant === 'quiet') return 'auto';
  return p.size === 's'
    ? `${p.theme.spacing.unit(8)}px`
    : `${p.theme.spacing.unit(10)}px`;
};

const height = css<Pick<Props, 'variant' | 'size'>>`
  height: ${(p) => calculateHeight(p)};
`;

```

2020-12-09 07:55 UTC, kmelkon commented on src/Molecules/Input/Text/Text.tsx
> +  ${(p) => (p.disabled ? `&:disabled::placeholder { color: ${p.theme.color.disabledText}}` : '')}
Might not be necessary, I can check. but I know that without the `:disabled` it doesn't work

2020-12-09 07:55 UTC, kmelkon commented on src/Molecules/Input/Number/Number.tsx
> +  height: ${(p) => (p.variant === 'quiet' ? 'auto' : '')};
bruh <3 I'll change it

2020-12-09 08:05 UTC, ratkosolar commented on src/Molecules/Input/Text/Text.tsx
> +  ${(p) => (p.disabled ? `&:disabled::placeholder { color: ${p.theme.color.disabledText}}` : '')}
ah okay, was just curious :D

2020-12-09 09:06 UTC, kmelkon commented on src/Molecules/Input/Text/Text.tsx
> +  ${(p) => (p.disabled ? `&:disabled::placeholder { color: ${p.theme.color.disabledText}}` : '')}
classic

2020-12-09 09:08 UTC, kmelkon commented on src/Molecules/Input/Text/Text.tsx
> +  ${(p) => (p.disabled ? `&:disabled::placeholder { color: ${p.theme.color.disabledText}}` : '')}
the prop check wasn't needed :D removed it

2020-12-09 09:55 UTC, victoriatomzik approved these changes

2020-12-09 10:09 UTC, mjmonline approved these changes
LGTM

2020-12-09 10:31 UTC, ratkosolar approved these changes

2020-12-09 10:32 UTC, merged