feat/move tooltip to popper.js
nordnet/ui pull request #810
Opened 2020-12-16 11:04 UTC by crewneck

https://jira.prod.nordnet.se/browse/DND-570  

We want to move away from @reachjs/tooltip since it currently does not support touch events. We decided on adding Popper.js since it has nice handling of Tooltip placement baked in. We did have to handle the logic of opening and closing the tooltip on our own, which was heavily inspired by @reachjs/tooltip source code.  

Visible changes are that you now can open tooltips on mobile (by touching the trigger element) and a new prop called “mode”, which allows the developer to decide if the tooltip should be triggered by hover or by click. Not providing this prop defaults to hover for backwards compatibility.

2020-12-16 11:57 UTC, victoriatomzik commented on src/Molecules/Tooltip/Tooltip.tsx
> +     want tooltips popupping up as you move your mouse around the page.
popping up*

2020-12-16 12:07 UTC, nn-davsko approved these changes

2020-12-16 12:45 UTC, ratkosolar commented on scripts/start-storybook.sh
> +# --no-dll is required to make popper-react work with storybook because storybook has the same dependency with older version
we have considered doing that too but after some thinking it seems like it might cause it to break again in the future if the version we use goes out of sync with the storybook one

2020-12-16 12:46 UTC, ratkosolar commented on src/Molecules/Tooltip/Tooltip.stories.tsx
> +          <Tooltip inModal label={label} position="left">
I think this was added by accident while testing the new tooltip

2020-12-17 07:56 UTC, ratkosolar requested changes
![image](https://user-images.githubusercontent.com/6464604/102459283-b21b8080-4045-11eb-9e15-5ae1adc33384.png)
I just noticed that the build script is broken due to storybook having the same dependency for react-popper but older version.... I remember we did that `--no-dll` in the dev script, maybe we can do the same for build?

2020-12-17 09:39 UTC, victoriatomzik requested changes
<img width="735" alt="image" src="https://user-images.githubusercontent.com/17315148/102470300-17766e00-4054-11eb-8606-f6195e203b7a.png">

2020-12-17 14:55 UTC, ratkosolar approved these changes

2020-12-17 15:12 UTC, victoriatomzik approved these changes

2020-12-21 10:22 UTC, merged