Feat/persist sort order for flex table
nordnet/ui pull request #841
Opened 2021-02-25 11:17 UTC by gustav-pettersson-nordnet

Need feedback on how to solve typescript error when trying to use **id** and **persistSortingOrder** from context.
I don't want to have them as device specific props.

2021-02-25 11:25 UTC, gustav-pettersson-nordnet commented on src/Molecules/FlexTable/shared/FlexTableProvider/FlexTableProvider.types.ts
> +  persistSortingOrder: boolean;
persistSortingOrder is part of FlexTableContextProps what I can see but I still get typescript error about It.

2021-02-25 17:11 UTC, jesperwiner requested changes

2021-02-25 17:11 UTC, jesperwiner commented on src/Molecules/FlexTable/shared/persistedSortOrder.ts
> +  const sortedSortOrders = localStorage.getItem(persistedSortOrderLocalStorageKey);
add a try/catch around all access to local storage please

2021-02-25 17:11 UTC, jesperwiner commented on src/Molecules/FlexTable/shared/persistedSortOrder.ts
> +  if (tableId && tableHasSavedPersistedSortOrder(tableId)) {
here too, we have found that some browsers will throw exceptions there that bubble all the way to the oops page

2021-02-26 07:56 UTC, almightybruce approved these changes
Looks good. I think you should be consistent between `sortOrder` and `sortingOrder`. And maybe `tableHasSavedPersistedSortOrder` can lose the _saved_

2021-03-01 08:01 UTC, jesperwiner approved these changes

2021-03-05 07:11 UTC, merged