fix: 🐛 Account for border height in Input phone component
nordnet/ui pull request #929
Opened 2021-06-14 14:32 UTC by NavidNayeri

2021-06-14 14:47 UTC, KitsuneKelso requested changes

2021-06-14 14:47 UTC, KitsuneKelso commented on src/Molecules/Input/Select/Select.tsx
> +          height={props.height}
We should add a story for this new prop.

2021-06-14 15:35 UTC, KitsuneKelso approved these changes

2021-06-15 07:14 UTC, anneback approved these changes

2021-06-15 07:15 UTC, merged