Feat/urgent message icon
nordnet/ui pull request #965
Opened 2021-09-03 13:58 UTC by anneback

2021-09-03 14:12 UTC, jesperwiner requested changes

2021-09-03 14:12 UTC, jesperwiner commented on src/Atoms/Icon/components/UrgentMessage.tsx
> +          strokeColorFn={stroke || (() => '#282823')}
Please don’t use hardcoded colors.

2021-09-06 08:05 UTC, jesperwiner approved these changes

2021-09-06 08:10 UTC, NavidNayeri approved these changes

2021-09-06 08:10 UTC, merged